### ISSUE TITLE
discontig block group on mutil-nodes: Remote mount failed:Deprecated parameter: cannot touch ‘/usr/local/ocfs2-test/log/o2t.log’

### ISSUE THREAD

**Issue by renzhengeek** [ganghe/ocfs2-test#10]
- 2015-03-20-13-49-58-discontig-bg.log
```
2015/03/20,13:49:58  =====================Discontiguous block groups tests start:  2015年 03月 20日 星期五 13:49:58 CST=====================
2015/03/20,13:49:58  <- Running test with 512 bs and 4096 cs ->
2015/03/20,13:49:58  [*] Multi-nodes Inodes Block Group Test:
2015/03/20,13:49:58  Activate inode discontig-bg on /dev/sdb1
[*] Mkfs device /dev/sdb1:                                                     [ PASS ]
[*] Change Volume Size                                                         [ PASS ]
[*] Mount /dev/sdb1 to /mnt/shared/:                                           [ PASS ]
[*] Fillup volume with huge unwritten region and small files:                  [ PASS ]
[*] Umount device /dev/sdb1                                                    [ PASS ]
[*] Fill up contiguous inode block groups:                                     [ PASS ]
2015/03/20,13:53:59  [*] Remote Mount among nodes n1,n2,n3:
2015/03/20,13:53:59  /opt/ocfs2-test/bin/remote_mount.py -l ocfs2-discontig-bg-tests-multi-nodes -m /mnt/shared/ -n n1,n2,n3 -o localalloc=0
--------------------------------------------------------------------------
A deprecated MCA parameter value was specified in the environment or
on the command line.  Deprecated MCA parameters should be avoided;
they may disappear in future releases.

  Deprecated parameter: orte_rsh_agent
--------------------------------------------------------------------------
--------------------------------------------------------------------------
A deprecated MCA parameter value was specified in the environment or
on the command line.  Deprecated MCA parameters should be avoided;
they may disappear in future releases.

  Deprecated parameter: orte_rsh_agent
--------------------------------------------------------------------------
--------------------------------------------------------------------------
A deprecated MCA parameter value was specified in the environment or
on the command line.  Deprecated MCA parameters should be avoided;
they may disappear in future releases.

  Deprecated parameter: orte_rsh_agent
--------------------------------------------------------------------------
+ /usr/lib64/mpi/gcc/openmpi/bin/mpirun -mca btl tcp,self -mca orte_rsh_agent ssh:rsh -np 3 --host n1,n2,n3 /opt/ocfs2-test/bin/command.py --mount -l ocfs2-discontig-bg-tests-multi-nodes -m /mnt/shared/ -o localalloc=0
--------------------------------------------------------------------------
A deprecated MCA parameter value was specified in the environment or
on the command line.  Deprecated MCA parameters should be avoided;
they may disappear in future releases.

  Deprecated parameter: orte_rsh_agent
--------------------------------------------------------------------------
--------------------------------------------------------------------------
A deprecated MCA parameter value was specified in the environment or
on the command line.  Deprecated MCA parameters should be avoided;
they may disappear in future releases.

  Deprecated parameter: orte_rsh_agent
--------------------------------------------------------------------------
--------------------------------------------------------------------------
A deprecated MCA parameter value was specified in the environment or
on the command line.  Deprecated MCA parameters should be avoided;
they may disappear in future releases.

  Deprecated parameter: orte_rsh_agent
--------------------------------------------------------------------------
touch: cannot touch ‘/usr/local/ocfs2-test/log/o2t.log’: No such file or directory
Traceback (most recent call last):
  File "/opt/ocfs2-test/bin/command.py", line 94, in <module>
    mt_options)
  File "/opt/ocfs2-test/bin/o2tf.py", line 428, in SudoMount
    logfile, 0, '')
  File "/opt/ocfs2-test/bin/o2tf.py", line 54, in printlog
    fd = open(logfile, 'a+', 0)
IOError: [Errno 2] No such file or directory: '/usr/local/ocfs2-test/log/o2t.log'
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[37230,1],2]
  Exit code:    1
--------------------------------------------------------------------------
2015/03/20,13:54:00  Remote mount failed
```

**Comment by renzhengeek** [comment]
setup on each node of the cluster must be the same.
